### PR TITLE
Shortcut for the GloryDuck files in simulation mode

### PR DESCRIPTION
**Pull request by TjarkMiener**
This PR will add the seed to the input string for the GloryDuck txt files.

### CODE REVIEW

**Comment by cosimoNigro** [comment]
Hi @TjarkMiener,
sorry, I received a notification only now about this.
The idea would be that the script `jointLklDM.C` becomes deprecated in the next release and we start using the executable `jointLklDM`, whose source is in `exec/jointLklDM.cc`.

Have you tried to build gLike with cmake as I requested [some time ago here](https://github.com/javierrico/gLike/pull/33#issuecomment-654131474), to check if the new executable works as the old script? 
To me it worked, as far as I could check with the mock data in this repository.

Maybe we should implement these fixes and changes already in `exec/jointLklDM.cc` rather than in the old `.C` that we'll discard anyhow?

**Comment by dkerszberg** [comment]
Hi @cosimoNigro 
I also missed that I have to admit. Can we keep both for a few more weeks? Tjark and I are finalizing the GloryDuck analysis and I would like to run it the "old way" first (all my scripts are ready for that) but I would also be happy to run it the "new way" (with the executable) to cross-check that they work both exactly the same :-)
@TjarkMiener could you push the same changes in the exec/jointLklDM:cc file?

Apart from that missing bit (thanks Cosimo!) the PR is ok for me!

**Comment by cosimoNigro** [comment]
Ok for me if you change both, thank you!

**Comment by TjarkMiener** [comment]
Hi @cosimoNigro! Sorry, I missed that too! I will have a closer look after the GloryDuck analysis and come back to you.

**Comment by javierrico** [comment]
Ok, I see just one problem, having to do with the release structure rather than the code:
If you want to use a code with these changes to produce publishable results, the changes should go into a release that can be properly referenced.
Now, I don't want to start a whole new _release branch_ (check [this](https://github.com/javierrico/gLike/wiki/Branch-releases-structure-and-log) if you don't know what that is) just for this minor thing, so I suggest that you request the pull to the latest release branch, i.e. v00.09, can you do that @TjarkMiener ?

**Comment by javierrico** [comment]
Please don't leave for too late moving this PR to the v00.09 branch
There is another minor bug fix recently merged there and  would like to issue the new release including both PRs, and also merging all changes to the master branch. Thanks

**Comment by TjarkMiener** [comment]
Is it solved by changing the base branch from master to v00.09? Sorry for opening #43.

**Pull request merged**
