### PR TITLE
importing gLike classes in python: a jupyter notebook example

### PR DESCRIPTION
**Pull request by cosimoNigro**
Hello @javierrico @dkerszberg,

with this PR I'd like to initiate the discussion on creating a python interface for `gLike`. 
As most of astrophysical software is being developed in this language it would be a nice feature to add and would ease the combination of `gLike` with other packages.

At the moment I just replicated the example in `gLike/scripts/testPoissonLkl.C` in a notebook:  `gLike/notebooks/test_PoissonLkl.ipynb`.

I used [pyROOT](https://root.cern.ch/pyroot), i.e. my `ROOT` is configured to be imported in python,  as a consequence classes built on `ROOT` objects can be imported as well. 
The trick can be done with a couple of lines (see notebook)
```python
from ROOT import gInterpreter, gSystem
gInterpreter.ProcessLine('#include "../include/PoissonLkl.h"')
gSystem.Load("../lib/libgLike.so")
```
after that `PoissonLkl` (or any other `gLike` class) enters the `ROOT` namespace and can be imported from it
```python
from ROOT import PoissonLkl
```

I think is a viable solution, a user would just need the `pyROOT` extension, that can be activated when compiling `ROOT` (I can add an entry in the wiki for that).
The disadvantage is that some `ROOT` objects do not have return types compatible with python (see the trick in the notebook to fetch `TGraph`'s x and y points). 

I'd suggest to merge this PR and to keep the discussion on the python wrapper in an issue.

### CODE REVIEW

**Comment by cosimoNigro** [comment]
P.S. if you do not have `pyROOT` you can see the notebook output in [my fork](https://github.com/cosimoNigro/gLike/blob/jupyter_notebooks/notebooks/test_PoissonLkl.ipynb).

**Comment by cosimoNigro** [comment]
I added a notebook reproducing in python the tutorial in `scripts/testJointLkl.C`, you can visualise it in [my fork](https://github.com/cosimoNigro/gLike/blob/jupyter_notebooks/notebooks/test_JointLkl.ipynb).

**Comment by javierrico** [comment]
> I added a notebook reproducing in python the tutorial in `scripts/testJointLkl.C`, you can visualise it in [my fork](https://github.com/cosimoNigro/gLike/blob/jupyter_notebooks/notebooks/test_JointLkl.ipynb).

Can you add this also to the PR?
Can the notebooks be in the scripts directory for the moment? 
Later, if the python wrapper options becomes fully established we can think of having a specific subdirectory

**Comment by cosimoNigro** [comment]
Do you prefer to have `scripts/notebooks` or the two jupyter notebooks directly in `scripts`?

**Comment by javierrico** [comment]
directly at scripts, we can reorder later if needed

El jue., 30 ene. 2020 a las 16:27, Cosimo Nigro
(<notifications@github.com>) escribió:
>
> Do you prefer to have ´scripts/notebooks´ or the two files directly in ´scripts´?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
---------------------------------------------------------
Javier RICO
Institut de Fisica d'Altes Energies (IFAE)
Barcelona Institute of Science and Technology (BIST)
Edifici Cn. Universitat Autonoma de Barcelona
08193 Bellaterra (Barcelona) Spain
Phone:  +34 93 164 1661
---------------------------------------------------------

--
Avís - Aviso - Legal Notice - (LOPD) - http://legal.ifae.es

-- 
Avís -
Aviso - Legal Notice - (LOPD) - http://legal.ifae.es 
<http://legal.ifae.es/>

**Comment by cosimoNigro** [comment]
Done! 
Moved in:
`scripts/test_JointLkl.ipynb` and `scripts/test_PoissonLkl.ipynb`

**Pull request merged**
